### ISSUE TITLE
Separate your webpage into sections

### ISSUE THREAD

**Issue by zannain** [UKipketer/prj-rev-bwfs-dasmoto#2]
When creating web pages you want to try and break up your HTML into sections. In the past, this was done with `div` tags but with the release of HTML5, there is a specific tag called `section` that you can use to break up your webpage. The benefit of this is that you are making your web page more accessible with HTML5's built-in Application Rich Internet Applications (ARIA) that provides a better user experience for individuals who have visual and auditory impairments. Another benefit is it makes your code easier to read and write when you have multiple sections of repeating code. Almost all text editors have code folding built in, so when your web page is broken up into `sections` you can fold multiple sections and this will help you debug and make it easier to make use of the `classes` I mentioned in a previous Issue.

For example, you have in your HTML page a common pattern. 

```html
<h2></h2>
<img></img>
<h3></h3>
<p><strong></strong></p> 
```
By breaking this up into sections, its easier to read:

```html
<section>
    <h2></h2>
    <img></img>
    <h3></h3>
    <p><strong></strong></p> 
</section>
```

**Comment by UKipketer** [comment]
ok got it thks !
