### ISSUE TITLE
Directory structure 

### ISSUE THREAD

**Issue by zannain** [UKipketer/prj-rev-bwfs-dasmoto#3]
When creating web pages it is considered by most a best practice to created separate directories for your stylesheets, assets and javascript files. Usually, you will find an `index.html` page that has a stylesheet referred to a directory call `css` and if the web page uses javascript there will be references to files within a `js` directory. Similarly, an `img` directory will contain all the references that an `img` element may reference.

**Comment by UKipketer** [comment]
Ok got it thks !
