### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by zannain** [UKipketer/prj-rev-bwfs-dasmoto#5]
Meets expectations

Great work on this mockup! You have mastered the basics of HTML and CSS and I encourage you to continue your journey by honing in on some of the finer details of these two languages. I've listed a few resources below for you to learn more about Flexbox which is a recent addition to CSS3 that revolutionizes how developers create responsive web pages. I encourage you to familiarize yourself with HTML5 elements as the will optimize your web page for search engines, make your web page more accessible to users that have auditory and visual impairments. Remember to always be aware of your code to never repeat yourself because if you are you should immediately ask yourself "Where can I refactor". This may not seem like a big deal now but as you start working on bigger projects, this will be a key concept when some applications can have 100's of views.  Best of luck and good luck to you on your journey to learn programming!

[HTML5 Elements](https://www.w3schools.com/html/html5_new_elements.asp)
[Flexbox Demo](https://codepen.io/dudleystorey/pen/Kgofa)
[Flexbox Demo](https://codepen.io/team/css-tricks/pen/EKEYob)
[CSS-Tricks Guide on Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
[Flexbox Course](https://flexbox.io/)

**Comment by UKipketer** [comment]
Links added to Favorites.
Thks !
